apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels: 
    app: {{ .Values.mysql.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.pvcStorage }}


