apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.dbServiceName }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
  type: ClusterIP
